import "./globals.css";
import { Inter } from "next/font/google";
import BottomNav from "@/components/bottomNav/BottomNav";
import AuthProvider from "@/provider/AuthProvider";
import TopNav from "@/components/topNav/TopNav";
import { QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "@/provider/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TopNav />
          <ReactQueryProvider>
            <main className="w-full flex justify-center max-w-screen-xl mx-auto grow">
              {children}
            </main>
          </ReactQueryProvider>
          <BottomNav />
        </AuthProvider>
      </body>
    </html>
  );
}
