import BottomNav from "@/components/base/BottomNav";
import TopNav from "@/components/base/TopNav";
import AuthProvider from "@/provider/AuthProvider";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import BottomCenterToast from "@/components/common/BottomCenterToast";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TopNav />
          <ReactQueryProvider>
            <main className="w-full flex max-w-screen-xl  mx-auto grow justify-center">
              {children}
            </main>
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryProvider>
          <BottomNav />
        </AuthProvider>
        <div id="portal" />
        <BottomCenterToast />
      </body>
    </html>
  );
}
