import Header from "@/components/topNav/TopNav";
import "./globals.css";
import { Inter } from "next/font/google";
import BottomNav from "@/components/bottomNav/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="w-full flex justify-center max-w-screen-xl mx-auto min-h-screen ">
          {children}
        </main>
        <BottomNav />
      </body>
    </html>
  );
}
